---
title: "R Notebook"
output: html_notebook
---

```{r}
library(data.table)
library(stringr)
```

```{r}
hand_coded <- fread("../results/hand-verif.csv", colClasses = "character")
head(hand_coded,2)
```

```{r}
cols <- names(hand_coded)
cols_sel <- cols[str_detect(cols, "((lin|tra)_pred\\d{1}_\\d)|class_count")]
hand_coded[, (cols_sel):=lapply(.SD, as.numeric), .SDcols= cols_sel]
hand_coded[ , .(class, lin_pred1)] 
```

Evaluation based on overlap

```{r}
hand_coded[, .SD, .SDcols = patterns("V1|class$|class_count|((lin|tra)_pred\\d{1}$)|class_count|source")] |>
  melt(id.vars = c("V1", "class", "source", "class_count")) |>
  {\(x) x[, id:=1:.N]}() |>
  {\(x) x[, ":="(class_l = str_extract_all(class, "\\d{6}"),
                 value_l = str_extract_all(value, "\\d{6}")), by = id]}() |>
  #subset(class_count > 1) |>
  {\(x) x[, ":="(overlap1 = length(intersect(substr(class_l[[1]],1,1), substr(value_l[[1]],1,1))) > 0,
                 overlap2 = length(intersect(substr(class_l[[1]],1,2), substr(value_l[[1]],1,2))) > 0,
                 overlap3 = length(intersect(substr(class_l[[1]],1,3), substr(value_l[[1]],1,3))) > 0,
                 overlap4 = length(intersect(substr(class_l[[1]],1,4), substr(value_l[[1]],1,4))) > 0,
                 overlap6 = length(intersect(substr(class_l[[1]],1,6), substr(value_l[[1]],1,6))) > 0), id][]}() |>
  #subset(class_count > 1)
{\(x) x[, lapply(.SD, mean), keyby=.(source, variable), .SDcols = patterns("overlap")]}() 
```

Confusion matrices

```{r}
xtabs(~ class1 + class1_lin, data = hand_coded, subset = source == "train") |>
  addmargins() |>
  xtable(digits = 0) 
  

xtabs(~ class1 + class1_lin, data = hand_coded, subset = source == "train") |> 
  prop.table(margin = 1) |>
  {\(x) round(x*100,1)}() |>
  xtable(digits = 1)

```
```{r}
xtabs(~ class1 + class1_lin, data = hand_coded, subset = source == "test") |>
  addmargins() |>
  xtable(digits=0) 

xtabs(~ class1 + class1_lin, data = hand_coded, subset = source == "test") |> 
  prop.table(margin = 1) |>
  {\(x) round(x*100,1)}() |>
  xtable(digits = 1)
```

```{r}
xtabs(~ class1 + class1_tra, data = hand_coded, subset = source == "train") |>
  addmargins() |>
  xtable(digits=0)

xtabs(~ class1 + class1_tra, data = hand_coded, subset = source == "test")  |>
  addmargins() |>
  xtable(digits=0)

xtabs(~ class1 + class1_tra, data = hand_coded, subset = source == "train") |> 
  prop.table(margin = 1) |>
  {\(x) round(x*100,1)}() |>
  xtable(digits = 1)

xtabs(~ class1 + class1_tra, data = hand_coded, subset = source == "test") |> 
  prop.table(margin = 1) |>
  {\(x) round(x*100,1)}() |>
  xtable(digits = 1)

```

